# Generated by Django 2.2.9 on 2020-01-17 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hood_photo', pyuploadcare.dj.models.ImageField(blank=True)),
                ('hood_name', models.CharField(blank=True, max_length=100, null=True)),
                ('occupants_count', models.IntegerField(blank=True, null=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', pyuploadcare.dj.models.ImageField(blank=True)),
                ('bio', models.CharField(max_length=240, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('u_hood', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='s.Hood')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_photo', pyuploadcare.dj.models.ImageField(blank=True)),
                ('b_name', models.CharField(blank=True, max_length=100, null=True)),
                ('b_description', models.TextField(blank=True, max_length=200, null=True)),
                ('b_email', models.CharField(blank=True, max_length=100, null=True)),
                ('hood', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='s.Hood')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
