# Generated by Django 2.2.9 on 2020-01-17 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s', '0002_auto_20200117_2350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hood',
            options={'ordering': ['hood_name']},
        ),
        migrations.AlterField(
            model_name='hood',
            name='occupants_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
