# Generated by Django 2.2.9 on 2020-01-18 10:21

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('s', '0005_auto_20200118_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hood',
            old_name='admin',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='business',
            name='b_photo',
            field=pyuploadcare.dj.models.ImageField(blank=True, null=True),
        ),
    ]
