# Generated by Django 2.2.9 on 2020-01-19 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s', '0007_auto_20200118_1536'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
